# Generated by Django 4.2.1 on 2023-05-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_price_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
