# Generated by Django 4.2.1 on 2023-05-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='q',
        ),
    ]
