# Generated by Django 4.2.1 on 2023-05-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_quantity_item_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='q',
            new_name='quantity',
        ),
    ]
