# Generated by Django 4.2.1 on 2023-05-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_q_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
